export const ProfileDataField = {
  PROFILE_TYPE: "profileType",
  ID: "id",
  VERSION: "version",
  USER_ID: "userId",
  INVESTOR: "investor",
  NAME: "name",
  NAME_FIRST: "firstName",
  NAME_LAST: "lastName",
  CONTACT_MOBILE: "mobile",
  CONTACT_EMAIL: "email",
  DATE_OF_BIRTH: "dateOfBirth",
  IDENTITY_DOC_ID: "nric",
  IDENTITY_DOC_COUNTRY: "countryOfIssuance",
  NATIONALITY: "nationality",
  BIRTH_COUNTRY: "countryOfBirth",
  RESIDENCE_COUNTRY: "addressCountryOfResidence",
  RESIDENCE_CITY: "addressCity",
  RESIDENCE_ADDRESS: "addressAddress",
  RESIDENCE_UNIT: "addressUnit",
  RESIDENCE_POSTAL_CODE: "addressPostal",
  MAILING_USE_RESIDENCE: "mailSameAsResidential",
  MAILING_COUNTRY: "mailAddressCountryOfResidence",
  MAILING_CITY: "mailAddressCity",
  MAILING_ADDRESS: "mailAddressAddress",
  MAILING_UNIT: "mailAddressUnit",
  MAILING_POSTAL_CODE: "mailAddressPostal",
  US_PERSON: "usPerson",
  EMPLOYMENT_STATUS: "employmentStatus",
  SOURCE_OF_WEALTH: "sourceOfWealth",
  SOURCE_OF_FUND: "sourceOfFund",
  SINGAPORE_TAX_RESIDENCE: "singaporeTaxResidence",
  TAX_COUNTRY: "taxCountry",
  TAX_RESIDENCE_ID: "tin",
} as const;

export const ALL_FIELDS_NAMES = Object.values(ProfileDataField);
export default ProfileDataField;
